doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            activity_type: App\Infrastructure\Activity\Orm\Doctrine\CustomType\ActivityTypeCustomType
            age: App\Infrastructure\User\Orm\Doctrine\CustomType\AgeCustomType
            description: App\Infrastructure\Activity\Orm\Doctrine\CustomType\DescriptionCustomType
            distance_value: App\Infrastructure\Common\Orm\Doctrine\CustomType\DistanceValueCustomType
            distance_unit: App\Infrastructure\Common\Orm\Doctrine\CustomType\DistanceUnitCustomType
            elapsed_time_value: App\Infrastructure\Common\Orm\Doctrine\CustomType\ElapsedTimeValueCustomType
            elapsed_time_unit: App\Infrastructure\Common\Orm\Doctrine\CustomType\ElapsedTimeUnitCustomType
            height: App\Infrastructure\User\Orm\Doctrine\CustomType\HeightCustomType
            name: App\Infrastructure\Activity\Orm\Doctrine\CustomType\NameCustomType
            weight: App\Infrastructure\User\Orm\Doctrine\CustomType\WeightCustomType

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Activity:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Activity/Orm/Doctrine/Mapping'
                prefix: 'App\Domain\Activity\Entity'
            Distance:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Common/Orm/Doctrine/Mapping'
                prefix: 'App\Domain\Common\ValueObject'
            ElapsedTime:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Common/Orm/Doctrine/Mapping'
                prefix: 'App\Domain\Common\ValueObject'
            Session:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Session/Orm/Doctrine/Mapping'
                prefix: 'App\Domain\Session\Entity'
            User:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/User/Orm/Doctrine/Mapping'
                prefix: 'App\Domain\User\Entity'
            Tracking:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Session/Orm/Doctrine/Mapping/ValueObject'
                prefix: 'App\Domain\Session\ValueObject'
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
