services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Infrastructure\Common\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Infrastructure\Common\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

  # Doctrine #
    App\Infrastructure\Activity\Repository\DoctrineActivityRepository:
        arguments:
            - '@doctrine'

  # UI / API #
    App\WebApi\Activity\Controller\GetActivityController:
        tags: [ 'controller.service_arguments' ]
        arguments:
            - '@App\WebApi\Activity\Converter\RequestToGetActivityQueryConverter'
            - '@App\Infrastructure\Common\Bus\Query\QueryBus'

    App\WebApi\Activity\Converter\RequestToGetActivityQueryConverter:

  # Application #
    App\Application\Activity\Query\GetActivity\GetActivityQueryHandler:
        tags: [messenger.message_handler]
        public: true
        arguments:
            - '@App\Infrastructure\Activity\Repository\DoctrineActivityRepository'

    App\WebApi\Activity\Controller\GetActivitiesController:
        tags: [ 'controller.service_arguments' ]
        arguments:
            - '@App\WebApi\Activity\Converter\RequestToGetActivitiesQueryConverter'
            - '@App\Infrastructure\Common\Bus\Query\QueryBus'

    App\WebApi\Activity\Converter\RequestToGetActivitiesQueryConverter:

  # Application #
    App\Application\Activity\Query\GetActivities\GetActivitiesQueryHandler:
        tags: [messenger.message_handler]
        public: true
        arguments:
            - '@App\Infrastructure\Activity\Repository\DoctrineActivityRepository'

    App\WebApi\Activity\Controller\CreateActivityController:
        tags: [ 'controller.service_arguments' ]
        arguments:
            - '@App\WebApi\Activity\Converter\RequestToCreateActivityCommandConverter'
            - '@App\Infrastructure\Common\Bus\Command\CommandBus'

    App\WebApi\Activity\Converter\RequestToCreateActivityCommandConverter:

    App\Application\Activity\Command\CreateActivity\CreateActivityCommandHandler:
        public: true
        arguments:
            - '@App\Infrastructure\Activity\Repository\DoctrineActivityRepository'

    App\Infrastructure\Common\Bus\Query\QueryBus:
        public: true
        class: App\Infrastructure\Common\Bus\Query\MessengerQueryBus

    App\Infrastructure\Common\Bus\Command\CommandBus:
        public: true
        class: App\Infrastructure\Common\Bus\Command\MessengerCommandBus